name: CustomEnchants
version: '${project.version}'
main: com.lgdtimtou.customenchants.Main
api-version: 1.18
authors: [ Timtou ]
description: A MineCraft plugin that adds new handy and fun enchantments to your server!

commands:
  customenchant:
    permission: customenchant.command.enchant
    aliases: [ce, cenchant, custome]
