load: STARTUP
name: CustomEnchants
version: '${project.version}'
main: be.timonc.customenchantments.Main
api-version: 1.20
authors: [ Timtou ]
description: A plugin that allows you to add custom enchantments to your server!
website: "www.timonc.be/custom_enchants"
softdepend:
  - PlaceholderAPI


commands:
  customenchant:
    aliases: [ ce, cenchant, custome ]
